package csv;

import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collections;

public class CSVObjects<E extends CSVEntity> {
	
	private CSVDocument			doc;
	private CSVObjectLoader<E>	csvloader;
	private CSVObjectSaver<E>	csvsaver;
	private CSVObjectDeleter<E>	csvdeleter;
	
	public CSVObjects(Class<? extends CSVEntity> c) throws IOException {
		super();
		this.doc = new CSVDocument(c);
		this.csvloader = new CSVObjectLoader<E>(c);
		this.csvsaver = new CSVObjectSaver<E>(doc);
		this.csvdeleter = new CSVObjectDeleter<E>(doc);
	}
	
	private String generateID() throws InvalidDataException {
		if (doc.lineCount() == 0)
			return "1";
		ArrayList<Integer> IDs = doc.getIDS();
		int generatedID = Collections.max(IDs) + 1;
		return Integer.toString(generatedID);
		
	}
	
	public void add(E e) throws IOException, InvalidCSVException, InvalidDataException, CSVUpdateException,
			NumberFormatException, ParseException {
		if (e.isAttached()) {
			throw new CSVUpdateException("Object is already attached");
		}
		if (getByID(e.csvID()) != null) {
			throw new InvalidCSVException("Object with ID= " + e.csvID() + " already exists in " + doc.getPath());
		}
		if (e.AutoGeneratedID()) {
			String generatedID = generateID();
			e.setCsvID(generatedID);
		}
		csvsaver.addObject(e);
	}
	
	public void addMany(Iterable<E> many) throws NumberFormatException, IOException, InvalidCSVException,
			InvalidDataException, CSVUpdateException, ParseException {
		for (E e : many) {
			add(e);
		}
	}
	
	public E getByID(String ID)
			throws IOException, InvalidCSVException, InvalidDataException, NumberFormatException, ParseException {
		CSVLine line = doc.getLineByID(ID);
		if (line == null) {
			return null;
		}
		return csvloader.createObject(line);
	}
	
	public void delete(E e) throws CSVUpdateException, IOException, InvalidCSVException {
		csvdeleter.deleteObject(e);
	}
	
	public void modify(E e) throws CSVUpdateException, IOException, InvalidCSVException, NumberFormatException,
			InvalidDataException, ParseException {
		delete(e);
		csvsaver.addObject(e);
	}
	
	public ArrayList<E> getAll()
			throws IOException, InvalidCSVException, InvalidDataException, NumberFormatException, ParseException {
		ArrayList<E> all = new ArrayList<>();
		for (CSVLine line : doc.getAll()) {
			all.add(csvloader.createObject(line));
		}
		return all;
	}
}
